spring.datasource.url=jdbc:postgresql://localhost:5432/epers_ejemplo_spring
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# DDL generation
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

# L2 Cache
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.region.factory_class=jcache
spring.jpa.properties.hibernate.cache.jcache.provider_class=com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
# spring.jpa.properties.hibernate.cache.use_query_cache=true

# Configuración global por defecto
spring.jpa.properties.hibernate.cache.caffeine.spec=maximumSize=500,expireAfterWrite=5m

# Configuración por regiones (Nombre completo de la clase o colección)
spring.jpa.properties.hibernate.cache.caffeine.ar.edu.unq.spring.modelo.Personaje.spec=maximumSize=100,expireAfterWrite=10m
# spring.jpa.properties.hibernate.cache.caffeine.ar.edu.unq.spring.modelo.Item.spec=maximumSize=1000,expireAfterWrite=1h
# spring.jpa.properties.hibernate.cache.caffeine.ar.edu.unq.spring.modelo.Personaje.inventario.spec=maximumSize=100,expireAfterWrite=5m